### ISSUE TITLE
[DOC] Update dev setup page to encourage contributors to install `skbase` in a new virtual environment

### ISSUE THREAD

**Issue by achieveordie** [sktime/skbase#132]
**Describe the documentation issue**

I'm not sure if there's a reason this hasn't been done already but I think it'll be better if we add a step in [`installation.rst`](https://github.com/sktime/skbase/blob/main/docs/source/user_documentation/installation.rst) asking the contributor to do all this in a fresh virtual environment to properly compartmentalize package dependencies.

**Suggest a concrete fix/improvement**

I can add a PR to improve our docs.

**Comment by fkiraly** [comment]
Makes sense, that makes it clearer.
