### ISSUE TITLE
[BUG] `clone` breaks when `skbase` is installed without `pytest`

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#177]
Calling an estimator's `clone` breaks  when `pytest` is not installed, due to accidental coupling to `pytest` as discussed here: https://github.com/sktime/sktime/issues/4544#issuecomment-1534505500

**Comment by fkiraly** [comment]
the same problem happens for `__eq__` as it also imports `deep_equals`, but that is not commonly used elsewhere

**Comment by LarsLZondag** [comment]
> @LarsLZondag, while we have your attention - do you have any wisdom on how to best test isolation of `pytest`?
> 
> The problem is, any testing that uses `pytest` has `pytest` already imported...

I am definitely not an expert on this, but what I tend to do is to not have my tests be part of my top level package. So in this case you have `skbase/testing/...` and `skbase/tests/...`. I would personally prefer them to not be part of the top level package (`skbase`).

You could either move everything related to tests to sit alongside `skbase`. So `./tests/...` etc. Or you could exclude the `testing` and `tests` folder from your package in `setup.cfg`, therefore preventing imports from any tests or utilities that should only be used for tests. Currently, there are apparently utilities that are used in both tests and the main code. This would separate those out (those utitlies should be part of the main code).

I hope this helps, but again, I don't know if this is the correct approach.

**Comment by fkiraly** [comment]
> I would personally prefer them to not be part of the top level package 

The subtle point is that `scikit-base` also provides the testing system, so what is in `testing` aren't tests, but components for the downstream package to build its own test framework...

> Currently, there are apparently utilities that are used in both tests and the main code. 

In consequence of the above, there will be utilities that are used by both the main code as well as the testing framework template, as `scikit-base` is a templating package, for both downstream classes and testing framework.

So, what you are saying may have to be adapted, because not all tests are tests of the package itself.

Though I suppose the suggestion to separate out the utilities makes a lot of sense, that's also the direction we (@yarnabrina) were thinking.

**Comment by fkiraly** [comment]
Either way, 0.4.3 should not longer hae the problem with `clone`. `__eq__` is still affected, but that should be solved by the moving of `deep_equals`.
