### ISSUE TITLE
`pytest` import triggered from main code

### ISSUE THREAD

**Issue by LarsLZondag** [sktime/skbase#180]
https://github.com/sktime/skbase/blob/9a5c70c358ef89b06993148407d93c524141e07a/skbase/base/_base.py#L96

This piece in the main code imports from the testing module. This import then triggers the following line of code:

https://github.com/sktime/skbase/blob/9a5c70c358ef89b06993148407d93c524141e07a/skbase/testing/__init__.py#L5

Which then imports `pytest`:

https://github.com/sktime/skbase/blob/9a5c70c358ef89b06993148407d93c524141e07a/skbase/testing/test_all_objects.py#L14

`pytest` is only part of the optional requirements and probably should not be imported in the main code unless it becomes part of the standard requirements. 

I ran into this issue in an environment that did not have `pytest` installed and I was calling `.clone()` on an estimator that inherited from `BaseObject`.

**Comment by fkiraly** [comment]
yes, this is a duplicate of this one here, right?
https://github.com/sktime/skbase/issues/177

**Comment by LarsLZondag** [comment]
Duplicate of #177

**Comment by fkiraly** [comment]
sorry for this @LarsLZondag - `__init__` logic is tricky...
