### ISSUE TITLE
[CI/CD] Add mypy to CI

### ISSUE THREAD

**Issue by RNKuhns** [sktime/skbase#25]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

It would be nice to add mypy to the project's CI suite.

**Describe the solution you'd like**
A clear and concise description of what you want to happen, ideally taking into consideration the existing toolbox design, classes and methods. 

Use pre-commit to add mypy to the project.

**Additional context**
I did not implement this initially, b/c there are currently a handful of mypy typing issues that need to be sorted out.

**Comment by fkiraly** [comment]
obsolete
