### ISSUE TITLE
Example module for testing

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#28]
I think we need a private example module for testing, e.g., one or two classes with tags inside.
Because we need to be able to test the test framework - which in this package, is the subject and not the means of testing!

I suggest the following sequence:

* get `all_objects` PR in, this is a conditionality
* I create example module
* I refactor the test classes based on example module

**Comment by RNKuhns** [comment]
@fkiraly that sounds good to me. The test module is needed to test the `all_objects` lookup too. Since we want that to work in this package, but also other packages that import it.

For the example module, where do we want that to live relative to the package's structure?

**Comment by RNKuhns** [comment]
@fkiraly I'll be adding this in a forthcoming PR for testing the lookup functionality.

**Comment by RNKuhns** [comment]
There is a mock package in the tests area that is now used for testing this functionality.
