### ISSUE TITLE
[MNT] python 3.13 compatibility

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#367]
We need to release a python 3.13 compatible version once 3.13 is released.

Overall strategy with sktime: https://github.com/sktime/sktime/issues/7190

For skbase, we should:

1. release experimental 3.13 wheels for reverse dependencies to test on
2. once 3.13 is released, full wheels

The PR https://github.com/sktime/skbase/pull/365 adds testing on 3.13 rc2.
The testing uses `sklearn`, which seems incompatible with 3.13 on windows.

For now, windows testing is skipped, but that should also be reverted.

Todos:

* change testing to test with 3.13 release version
* add 3.13 tests to release workflow

**Comment by fkiraly** [comment]
FYI @MCRE-BE

Thanks for taking care of the `conda` feedstock!

Just to let you know that for 0.11.0 we need to update the python bounds.

**Comment by MCRE-BE** [comment]
No problem. I'll push the changes.

**Comment by MCRE-BE** [comment]
Should be fine.

**Comment by fkiraly** [comment]
Great - we can close 3.13 then.
