### ISSUE TITLE
[ENH] Dependency handling

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#40]
While reading the docs: we probably want to think about dependencies. Some points:

* this is a "base" style package, so we probably want to minimize dependencies absolutely, possibly to zero! So, `typing-extensions` and `pytest` out from the core dependency set.
* not sure about `typing-extensions`, is that really necessary?
* `pytest` is necessary for the test framwork, but I would also think about making it optional, now that I looked at it
* re soft dependencies, I think we may even want to adopt a policy that there won't be any! We also don't want to add any estimators to the package with the python verison tags etc, but we may like to provide users with that feature.

(not for 0.1.0)

**Comment by RNKuhns** [comment]
@fkiraly I generally agree with this. I want to get dependencies to zero if possible.

typing-extensions is only needed for the mypy type checking. We can look into type stubs and whether that will let us separate the need for typing-extensions from the actual code implementations.

Let's think through the pytest part. I do think having functionality to make testing easier for other developers is a nice have. We could go the soft dependency route, or something else.

**Comment by fkiraly** [comment]
I would just stick it into a `dev` dependency set like we do in `sktime` - users don't need it, and it's nice for developers.
Although without `typing-extensions` the code would break, I think? Or can it be isolated?

**Comment by RNKuhns** [comment]
@fkiraly I actually realized that it would break the code. I think in version 0.4.0 or 0.5.0 we can consider moving away from ``TypedDict`` return in `get_package_metadata`.

Also note that ``TypedDict`` was introduced in version 3.8, so the need for typing-extensions is specific to our support for `Python=3.7.*`. The end of life for that Python version is in about 5 months, so we could also choose to wait this out and the need to have `typing-extensions` as a dependency goes away.

**Comment by fkiraly** [comment]
> The end of life for that Python version is in about 5 months

Python 3.7 is moribund? How sad. You were so familiar, good friend...

But it's good news we can get away from `typing-extensions` then. Perhaps we can just drop it now, then?

**Comment by fkiraly** [comment]
I've removed the dependencies now, there are no more dependencies.
