### ISSUE TITLE
[ENH] raise test coverage to >80%

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#49]
We need to raise test coverage of the package to higher, this will likely include:

* tests for the testing framework
* porting of base class tests from sktime
* writing new base class tests

Running List of Needed Tests:

- #63 
- #61
- #86
- #66

**Comment by RNKuhns** [comment]
@fkiraly this makes sense. I'm going to update the issue to include a list of all the different functionality we aren't currently testing. Then we can make individual issues for the items in the list.

**Comment by RNKuhns** [comment]
#62 should handle #61 and #63. I'll move onto the `skbase._lookup` functionality while you review.

**Comment by RNKuhns** [comment]
We've met this threshold. Closing.
