### ISSUE TITLE
Experimental Draft of sktime depending on package

### ISSUE THREAD

**Issue by RNKuhns** [sktime/skbase#6]
@fkiraly update: work in progress, in these PR:

* package dependencies, `sktime` `BaseObject`: https://github.com/sktime/sktime/pull/3151
* retrieval/lookup via `all_objects`: https://github.com/sktime/sktime/pull/3777

---

Open a PR in sktime that imports BaseObject from pypi project.

**Comment by RNKuhns** [comment]
This is dependent on their being a first working release (0.1.0) for the sktime PR to import and use.

**Comment by fkiraly** [comment]
I think we could also start with URL/GitHub import

**Comment by fkiraly** [comment]
First step to this: https://github.com/alan-turing-institute/sktime/pull/3122

On `sktime` side, delineates `BaseObject` functionality and tests, from `BaseEstimator` related scope.

**Comment by fkiraly** [comment]
draft PR with `sktime` on `skbase` dependency: https://github.com/sktime/sktime/pull/3150

currently direct github import, needs to change to pypi import

**Comment by fkiraly** [comment]
updated with pypi dependencies and more refactor points

**Comment by fkiraly** [comment]
done, now part of `sktime` and released with `skbase` dependency.
