### ISSUE TITLE
[BUG] `BaseObject._get_init_signature()` if statement never True?

### ISSUE THREAD

**Issue by RNKuhns** [sktime/skbase#65]
**Describe the bug**

`BaseObject._get_init_signature()` returns the init signature of a `BaseObject`. It starts off with code to shortcut the rest of the calculations if we notice that the returned init dunder is the same for the basic Python `object`. This never seems to be True since `BaseObject` currently inherits from scikit-learn's `BaseEstimator`. 

A snapshot of the related code (from the beginning lines of the `_get_init_signature` class method:

```python

init = getattr(cls.__init__, "deprecated_original", cls.__init__)
if init is object.__init__:
    # No explicit constructor to introspect
    return []
```
For example, the following indicates that `BaseObject's` will not return True for the if condition:

```python
from skbase import BaseObject
FIXTURE_BASEOBJECT = BaseObject
init = getattr(
    FIXTURE_BASEOBJECT.__init__, "deprecated_original", FIXTURE_BASEOBJECT.__init__
)
print(init is object.__init__)  # False
print(init == object.__init__)  # False
```

However, this code will be useful once we remove the inherittance from scikit-learn's `BaseEstimator`:

```python
class InitSignatureTester:

    @classmethod
    def _get_init_signature(cls):
        """Get class init sigature.

        Useful in parameter inspection.

        Returns
        -------
        List
            The inspected parameter objects (including defaults).

        Raises
        ------
        RuntimeError if cls has varargs in __init__.
        """
        # fetch the constructor or the original constructor before
        # deprecation wrapping if any
        init = getattr(cls.__init__, "deprecated_original", cls.__init__)
        if init is object.__init__:
            # No explicit constructor to introspect
            return []
        else:
            return "Rest code is run"


FIXTURE_BASEOBJECT = InitSignatureTester
init = getattr(
    FIXTURE_BASEOBJECT.__init__, "deprecated_original", FIXTURE_BASEOBJECT.__init__
)
print(init is object.__init__)  # True
print(init == object.__init__)  # True
```

**Expected behavior**

Conditional code should sometimes be True or it is not needed. In this case, we will need the code later once we finish refactoring so we don't inherit from `BaseEstimator`. Simiarly, the part of this code accounting for "deprecated_original" is related to how scikit-learn handles/handled deprecation. We may or may not want to retain that portion.

This issue is just to raise awareness in the meantime.

**Comment by fkiraly** [comment]
Yes, you are completely right!

Since `BaseObject` has an `__init__`, the condition will never be triggered.

**Comment by fkiraly** [comment]
addressed.
