### ISSUE TITLE
[ENH] Tag manager design - for skbase

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#67]
I would like to get some feedback on the tag manager design here: https://github.com/sktime/sktime/pull/3630

Before I merge this in `sktime` - should we have this in `skbase`?

**Comment by fkiraly** [comment]
what are your plans on the tag manager?

**Comment by RNKuhns** [comment]
@fkiraly i think we should try to include it in this release.

But I think we leave off the specific config implementation until next release. I’m still having trouble thinking about how this interacts with global config. But that doesn’t stop us from having flag manager behind the scenes and use it in get set/params.

Are you up for adding a PR with flag manager and tests like you proposed for sktime?

**Comment by fkiraly** [comment]
sure!

The global config could be added like here:
https://github.com/sktime/sktime/pull/4268
but I agree it might be worth thinking about it. As the PR shows, it should be possible to integrate it later.

**Comment by RNKuhns** [comment]
@fkiraly I'm thinking this issue is complete. We can open a separate issue for the global config interface and extension point.
