### ISSUE TITLE
rename `ignore_modules` to `modules_to_ignore`?

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#70]
In the `all_objects` module, we currently have inconsistent naming of the same type of argument, `ignore_modules` and `modules_to_ignore`.

I think we should consistently rename this to `modules_to_ignore`, because `ignore_modules` sounds like a boolean condition (e.g., "ignore modules?" - yes/no).

**Comment by RNKuhns** [comment]
This is fixed in #80.
