### ISSUE TITLE
[ENH] Port updated base class functionality from sktime

### ISSUE THREAD

**Issue by RNKuhns** [sktime/skbase#83]
**Is your feature request related to a problem?**

Since `skbase` initially ported over functionality from `sktime` there has been parallel development. The features should be synced up. 

**Describe the solution you'd like**

Sync up features in `skbase` with those in `sktime`.

**Comment by RNKuhns** [comment]
While under the hood working on this, it probably makes sense to also fix #65 and #81

**Comment by fkiraly** [comment]
sure!

**Comment by fkiraly** [comment]
should I do this?

**Comment by RNKuhns** [comment]
> should I do this?

It's yours!

**Comment by RNKuhns** [comment]
@fkiraly do we know of any other functionality that hasn't been ported over?

**Comment by fkiraly** [comment]
only this, I think:
https://github.com/sktime/skbase/issues/124

**Comment by fkiraly** [comment]
done
