### ISSUE TITLE
release 0.3.0 with `all_objects` fix?

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#84]
Hello @RNKuhns, when is release 0.3.0 with the fix in the `all_objects` utility coming?
I'm still blocked with `sktime` integration due to that - let me know if I can help.

**Comment by RNKuhns** [comment]
@fkiraly holdup was PR #80. But that should now be ready for review.

I have some minor documentation items I'd like to include (including release notes from prior release). Want to release on Friday (pending review of PR #80)?
