### ISSUE TITLE
[ENH] Enable skbase to be published on conda-forge

### ISSUE THREAD

**Issue by RNKuhns** [sktime/skbase#92]
**Is your feature request related to a problem? Please describe.**
`skbase` is currently only available on pypi. Following the release of version 0.3.0 , it would be great to be able to release versions on conda-forge as well. Particularly since some users are restricted by work or other institutional policy for using conda.
 
This should be more straightforward than with `sktime` since we don't have to worry about dependencies that aren't available on conda.

**Comment by fkiraly** [comment]
you mean, "only available on pypi"?

**Comment by RNKuhns** [comment]
> you mean, "only available on pypi"?

Fixed!

**Comment by fkiraly** [comment]
Post-hoc edits like that make me look like a rambling crazy person. I like it. 😁

**Comment by RNKuhns** [comment]
> Post-hoc edits like that make me look like a rambling crazy person. I like it. 😁

Haha. I guess it does look like that. But atleast if people read down they can see I fixed it and that's why!

**Comment by RNKuhns** [comment]
This is in progress via conda-forge/staged-recipes#21710. Will make PR in ``skbase`` to update installl documentation once conda-forge package is available.

**Comment by RNKuhns** [comment]
The conda-forge/staged-recipes#21710 is now passing all its CI checks. Hopefully after a review it will be able to be merged and I'll update the docs.

**Comment by RNKuhns** [comment]
Still waiting for conda-forge/staged-recipes#21710 to be reviewed and merged.

**Comment by RNKuhns** [comment]
Note that https://github.com/conda-forge/staged-recipes/pull/21710 has been approved. So we are just waiting for someone with merge authority to approve. Once that happens I'll update the docs to include conda installation.

**Comment by fkiraly** [comment]
It's merged now

**Comment by RNKuhns** [comment]
Great, I’ll close the issue!
