### ISSUE TITLE
Description and tags

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#94]
This repository should have a description and tags. Description can be bootstrapped from the README easily, while I'm not sure what to say for "tags".

Is there a tag for a framework for frameworks? "meta-framework"?

**Comment by RNKuhns** [comment]
I added a description to "about" section of github. By tags, do you mean the "topics" in the "about" section of github?

**Comment by fkiraly** [comment]
yes, that's precisely what I meant. Sorry for being unclear.

**Comment by RNKuhns** [comment]
No problem at all. I'll look into the topics.

**Comment by RNKuhns** [comment]
@fkiraly I've added the description and tags. There was an existing topic for "frameworks". If things look good on the homepage, you can close this.

**Comment by RNKuhns** [comment]
Also -- feel free to edit those if needed and then close. Either way, once you take a look you can close.
