### ISSUE TITLE
nice composition diagram from `sklearn`

### ISSUE THREAD

**Issue by fkiraly** [sktime/skbase#97]
Since the more recent versions of `sklearn`, composite estimators inheriting from `BaseEstimator` display like this:

![image](https://user-images.githubusercontent.com/7985502/210286140-1aba20bd-4e7c-4e07-8ec4-6e039de4a6e7.png)

This is currently not supported by `BaseObject` - but it would be nice if it were?

Nb, `sktime` `BaseObject` *does* support it, as it inherits the display method from `sklearn`.

**Comment by RNKuhns** [comment]
Yep -- it does. It is one of the tricker parts of the dependency to remove.

**Comment by RNKuhns** [comment]
We have #17 open related to the preservation of pretty printing (this is and printing classes nicely is part of that) when `sklearn` dependency is removed. Closing this as we'll make sure to retain this functionality as part of that issue.
